stages:
    - Windows Build

set-environment-job:
    stage: Windows Build
    script:
        - "& $CI_PROJECT_DIR/scripts/windows_minions.ps1 $WINDOWS_QT_PATH"
        - "echo $SourcesDir"
        - "& $CI_PROJECT_DIR/scripts/windows_minions.ps1 CleanBuild"
    tags:
        - win64

clean-build-job:      
    stage: Windows Build
    script:
        - "& $CI_PROJECT_DIR/scripts/windows_minions.ps1 CleanBuild"
    tags:
        - win64