stages:
    - Set Environment
    - Clean Build

environment-job:
    stage: Set Environment
    script:
        - "echo $CI_PROJECT_DIR/scripts/"
    tags:
        - win64

build-job:      
    stage: Clean Build
    script:
        - "$CI_PROJECT_DIR\\scripts\\windows_minions.ps1 CleanBuild"
    tags:
        - win64