stages:
    - Set Environment
    - Clean Build

environment-job:
    stage: Set Environment
    script:
        - "powershell -File $CI_PROJECT_DIR/scripts/windows_minions.ps1"
    tags:
        - win64

build-job:      
    stage: Clean Build
    script:
        - "powershell -File $CI_PROJECT_DIR/scripts/windows_minions.ps1 CleanBuild"
    tags:
        - win64