stages:
    - Windows Build

clean-build-job:      
    stage: Windows Build
    variables:
        QT_PATH: $WIN_QT_PATH
    script:
        - "& $CI_PROJECT_DIR/scripts/windows_minions.ps1 CleanBuild"
    tags:
        - win64