stages:
    - build
    - test

build windows:      
    stage: build
    variables:
        QT_PATH: $WIN_QT_PATH
    script:
        - "& $CI_PROJECT_DIR/scripts/windows_minions.ps1 CleanBuild"
    artifacts:
        paths:
            - "out/"
    tags:
        - win64

test windows:
    stage: test
    variables:
        QT_PATH: $WIN_QT_PATH
    script:
        - "& $CI_PROJECT_DIR/scripts/windows_minions.ps1 RunTests"
    dependencies:
        - "build windows"
    tags:
        - win64